#!/bin/sh
# Copyright (C) 2026 Huidae Cho <https://idea.isnew.info/>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

[ $# -eq 0 ] && { echo "Usage: embed-tikzcsv file.tex..."; exit 1; }

for tex; do
	[ -f "$tex" ] || continue

	case "$tex" in
	csv-*.tex)
		continue
		;;
	*.tex)
		;;
	*)
		continue
		;;
	esac

	csvtex="csv-$tex"

	for i in $(sed -E 's/%.*//; /\.csv/!d; s/.*\{([^}]*\.csv)\}.*/\1/' "$tex"); do
		[ -f "$i" ] || continue
		sed -E "s/($i)/\\
% \\1\\
\\1\\
/" "$tex" | sed "/^$i$/{
			r $i
			d
		}"
	done > "$csvtex"

	[ -s "$csvtex" ] || { rm -f "$csvtex"; continue; }

	cmp -s "$tex" "$csvtex" && rm -f "$csvtex"

	echo "$csvtex generated"
done
